sudo: required

language: node_js
node_js:
  - 12

services:
  - docker

before_install:
  - echo "Testing Docker Hub credentials"
  - docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  - echo "Docker Hub credentials are working"
  - docker build -t smartbrain_api .

script:
  # - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  # - echo "Repo is $REPO, commit is $TRAVIS_COMMIT, tag is $TAG, travis builder number is $TRAVIS_BUILD_NUMBER"
  - docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  - export REPO=vaibzzz1234/smartbrain_api
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$TRAVIS_COMMIT .
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
  - echo "Dockerhub push complete!"
