sudo: required

language: node_js

# services:
  # - docker

script:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  # - echo "Hello this is running properly"
