sudo: required

language: node_js

# services:
  # - docker

script:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - echo "Repo is $REPO, commit is $COMMIT, tag is $TAG, travis builder number is $TRAVIS_BUILD_NUMBER"
  # - echo "Hello this is running properly"
